name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liQwziWBChQhmiUt"
GITHUB_OWNER = "Chuyiyue"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navs.oonn.me/api/auth"
NEXT_PUBLIC_API_URL="https://navs.oonn.me"
GITHUB_SECRET="b094f0ca9f88a8b71a12ee4f45188bb8435fe115"
